# Generated by Django 2.0.2 on 2019-09-30 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='link',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='pub_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='title',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
